/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
import jogovelha.Jogador;
import jogovelha.Operacoes;

/**
 *
 * @author José Wilson Grilo
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    Jogador j1 = new Jogador();
    Jogador j2 = new Jogador();

    public Tela(Jogador j1, Jogador j2) {
        this.j1 = j1;
        this.j2 = j2;
        initComponents();
    }

    private Tela() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jB_L2C2 = new javax.swing.JButton();
        jTF_vez_jogada = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jB_L0C0 = new javax.swing.JButton();
        jB_L0C1 = new javax.swing.JButton();
        jB_L0C2 = new javax.swing.JButton();
        jB_L1C0 = new javax.swing.JButton();
        jB_L1C1 = new javax.swing.JButton();
        jB_L1C2 = new javax.swing.JButton();
        jB_L2C0 = new javax.swing.JButton();
        jB_L2C1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jB_L2C2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_L2C2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_L2C2MouseClicked(evt);
            }
        });

        jTF_vez_jogada.setEditable(false);
        jTF_vez_jogada.setEnabled(false);
        jTF_vez_jogada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_vez_jogadaActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("VEZ DA JOGADA");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("JOGO DA VELHA");

        jB_L0C0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_L0C0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_L0C0MouseClicked(evt);
            }
        });

        jB_L0C1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_L0C1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_L0C1MouseClicked(evt);
            }
        });

        jB_L0C2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_L0C2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_L0C2MouseClicked(evt);
            }
        });

        jB_L1C0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_L1C0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_L1C0MouseClicked(evt);
            }
        });

        jB_L1C1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_L1C1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_L1C1MouseClicked(evt);
            }
        });

        jB_L1C2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_L1C2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_L1C2MouseClicked(evt);
            }
        });

        jB_L2C0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_L2C0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_L2C0MouseClicked(evt);
            }
        });

        jB_L2C1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_L2C1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_L2C1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jB_L2C0, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jB_L1C0, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jB_L0C0, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jB_L2C1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jB_L2C2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jB_L0C1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jB_L1C1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jB_L0C2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jB_L1C2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(55, 55, 55))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jTF_vez_jogada, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_L0C0, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_L0C1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_L0C2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_L1C0, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_L1C1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_L1C2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_L2C0, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_L2C1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_L2C2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(jTF_vez_jogada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTF_vez_jogadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_vez_jogadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_vez_jogadaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

        // INICIA PARTIDA COM O JOGADOR INICIANTE
        if (j1.isVez_jogada()) {
            jTF_vez_jogada.setText("Jogador 1");
        }
        if (j2.isVez_jogada()) {
            jTF_vez_jogada.setText("Jogador 2");
        }
        

    }//GEN-LAST:event_formWindowActivated

    private void jB_L0C0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_L0C0MouseClicked
        // TODO add your handling code here:
        if (j1.isVez_jogada()) {
            if (jB_L0C0.getText().equals("")) {
                jB_L0C0.setText(j1.getDesenho());

                Operacoes op1 = new Operacoes();
                if (op1.verificarDiagonalPrincipal(jB_L0C0.getText(), jB_L1C1.getText(), jB_L2C2.getText(), j1.getDesenho())
                        || op1.verificarDiagonalSecundaria(jB_L0C2.getText(), jB_L1C1.getText(), jB_L2C0.getText(), j1.getDesenho())
                        || op1.verificarColuna0(jB_L0C0.getText(), jB_L1C0.getText(), jB_L2C0.getText(), j1.getDesenho())
                        || op1.verificarColuna1(jB_L0C1.getText(), jB_L1C1.getText(), jB_L2C1.getText(), j1.getDesenho())
                        || op1.verificarColuna2(jB_L0C2.getText(), jB_L1C2.getText(), jB_L2C2.getText(), j1.getDesenho())
                        || op1.verificarLinha0(jB_L0C0.getText(), jB_L0C1.getText(), jB_L0C2.getText(), j1.getDesenho())
                        || op1.verificarLinha1(jB_L1C0.getText(), jB_L1C1.getText(), jB_L1C2.getText(), j1.getDesenho())
                        || op1.verificarLinha2(jB_L2C0.getText(), jB_L2C1.getText(), jB_L2C2.getText(), j1.getDesenho())) {
                    JOptionPane.showMessageDialog(rootPane, "Jogador 1 !", "Jogador Vencedor", 1);
                } else {
                    j1.setVez_jogada(false);
                    j2.setVez_jogada(true);
                    jTF_vez_jogada.setText("Jogador 2");
                }
            }
        }
        if (j2.isVez_jogada()) {
            if (jB_L0C0.getText().equals("")) {
                jB_L0C0.setText(j2.getDesenho());
                
                Operacoes op2 = new Operacoes();
                if (op2.verificarDiagonalPrincipal(jB_L0C0.getText(), jB_L1C1.getText(), jB_L2C2.getText(), j2.getDesenho())
                        || op2.verificarDiagonalSecundaria(jB_L0C2.getText(), jB_L1C1.getText(), jB_L2C0.getText(), j2.getDesenho())
                        || op2.verificarColuna0(jB_L0C0.getText(), jB_L1C0.getText(), jB_L2C0.getText(), j2.getDesenho())
                        || op2.verificarColuna1(jB_L0C1.getText(), jB_L1C1.getText(), jB_L2C1.getText(), j2.getDesenho())
                        || op2.verificarColuna2(jB_L0C2.getText(), jB_L1C2.getText(), jB_L2C2.getText(), j2.getDesenho())
                        || op2.verificarLinha0(jB_L0C0.getText(), jB_L0C1.getText(), jB_L0C2.getText(), j2.getDesenho())
                        || op2.verificarLinha1(jB_L1C0.getText(), jB_L1C1.getText(), jB_L1C2.getText(), j2.getDesenho())
                        || op2.verificarLinha2(jB_L2C0.getText(), jB_L2C1.getText(), jB_L2C2.getText(), j2.getDesenho())) {
                    JOptionPane.showMessageDialog(rootPane, "Jogador 2 !", "Jogador Vencedor", 1);
                }else{
                    j2.setVez_jogada(false);
                    j1.setVez_jogada(true);
                    jTF_vez_jogada.setText("Jogador 1");
                }
            }
        }
    }//GEN-LAST:event_jB_L0C0MouseClicked

    private void jB_L0C1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_L0C1MouseClicked
        // TODO add your handling code here:
        if (j1.isVez_jogada()) {
            if (jB_L0C1.getText().equals("")) {
                jB_L0C1.setText(j1.getDesenho());

                Operacoes op1 = new Operacoes();
                if (op1.verificarDiagonalPrincipal(jB_L0C0.getText(), jB_L1C1.getText(), jB_L2C2.getText(), j1.getDesenho())
                        || op1.verificarDiagonalSecundaria(jB_L0C2.getText(), jB_L1C1.getText(), jB_L2C0.getText(), j1.getDesenho())
                        || op1.verificarColuna0(jB_L0C0.getText(), jB_L1C0.getText(), jB_L2C0.getText(), j1.getDesenho())
                        || op1.verificarColuna1(jB_L0C1.getText(), jB_L1C1.getText(), jB_L2C1.getText(), j1.getDesenho())
                        || op1.verificarColuna2(jB_L0C2.getText(), jB_L1C2.getText(), jB_L2C2.getText(), j1.getDesenho())
                        || op1.verificarLinha0(jB_L0C0.getText(), jB_L0C1.getText(), jB_L0C2.getText(), j1.getDesenho())
                        || op1.verificarLinha1(jB_L1C0.getText(), jB_L1C1.getText(), jB_L1C2.getText(), j1.getDesenho())
                        || op1.verificarLinha2(jB_L2C0.getText(), jB_L2C1.getText(), jB_L2C2.getText(), j1.getDesenho())) {
                    JOptionPane.showMessageDialog(rootPane, "Jogador 1 !", "Jogador Vencedor", 1);
                } else {
                    j1.setVez_jogada(false);
                    j2.setVez_jogada(true);
                    jTF_vez_jogada.setText("Jogador 2");
                }
            }
        }
        if (j2.isVez_jogada()) {
            if (jB_L0C1.getText().equals("")) {
                jB_L0C1.setText(j2.getDesenho());
                
                Operacoes op2 = new Operacoes();
                if (op2.verificarDiagonalPrincipal(jB_L0C0.getText(), jB_L1C1.getText(), jB_L2C2.getText(), j2.getDesenho())
                        || op2.verificarDiagonalSecundaria(jB_L0C2.getText(), jB_L1C1.getText(), jB_L2C0.getText(), j2.getDesenho())
                        || op2.verificarColuna0(jB_L0C0.getText(), jB_L1C0.getText(), jB_L2C0.getText(), j2.getDesenho())
                        || op2.verificarColuna1(jB_L0C1.getText(), jB_L1C1.getText(), jB_L2C1.getText(), j2.getDesenho())
                        || op2.verificarColuna2(jB_L0C2.getText(), jB_L1C2.getText(), jB_L2C2.getText(), j2.getDesenho())
                        || op2.verificarLinha0(jB_L0C0.getText(), jB_L0C1.getText(), jB_L0C2.getText(), j2.getDesenho())
                        || op2.verificarLinha1(jB_L1C0.getText(), jB_L1C1.getText(), jB_L1C2.getText(), j2.getDesenho())
                        || op2.verificarLinha2(jB_L2C0.getText(), jB_L2C1.getText(), jB_L2C2.getText(), j2.getDesenho())) {
                    JOptionPane.showMessageDialog(rootPane, "Jogador 2 !", "Jogador Vencedor", 1);
                }else{
                    j2.setVez_jogada(false);
                    j1.setVez_jogada(true);
                    jTF_vez_jogada.setText("Jogador 1");
                }
            }
        }
    }//GEN-LAST:event_jB_L0C1MouseClicked

    private void jB_L0C2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_L0C2MouseClicked
        // TODO add your handling code here:
        if (j1.isVez_jogada()) {
            if (jB_L0C2.getText().equals("")) {
                jB_L0C2.setText(j1.getDesenho());

                Operacoes op1 = new Operacoes();
                if (op1.verificarDiagonalPrincipal(jB_L0C0.getText(), jB_L1C1.getText(), jB_L2C2.getText(), j1.getDesenho())
                        || op1.verificarDiagonalSecundaria(jB_L0C2.getText(), jB_L1C1.getText(), jB_L2C0.getText(), j1.getDesenho())
                        || op1.verificarColuna0(jB_L0C0.getText(), jB_L1C0.getText(), jB_L2C0.getText(), j1.getDesenho())
                        || op1.verificarColuna1(jB_L0C1.getText(), jB_L1C1.getText(), jB_L2C1.getText(), j1.getDesenho())
                        || op1.verificarColuna2(jB_L0C2.getText(), jB_L1C2.getText(), jB_L2C2.getText(), j1.getDesenho())
                        || op1.verificarLinha0(jB_L0C0.getText(), jB_L0C1.getText(), jB_L0C2.getText(), j1.getDesenho())
                        || op1.verificarLinha1(jB_L1C0.getText(), jB_L1C1.getText(), jB_L1C2.getText(), j1.getDesenho())
                        || op1.verificarLinha2(jB_L2C0.getText(), jB_L2C1.getText(), jB_L2C2.getText(), j1.getDesenho())) {
                    JOptionPane.showMessageDialog(rootPane, "Jogador 1 !", "Jogador Vencedor", 1);
                } else {
                    j1.setVez_jogada(false);
                    j2.setVez_jogada(true);
                    jTF_vez_jogada.setText("Jogador 2");
                }
            }
        }
        if (j2.isVez_jogada()) {
            if (jB_L0C2.getText().equals("")) {
                jB_L0C2.setText(j2.getDesenho());
                
                Operacoes op2 = new Operacoes();
                if (op2.verificarDiagonalPrincipal(jB_L0C0.getText(), jB_L1C1.getText(), jB_L2C2.getText(), j2.getDesenho())
                        || op2.verificarDiagonalSecundaria(jB_L0C2.getText(), jB_L1C1.getText(), jB_L2C0.getText(), j2.getDesenho())
                        || op2.verificarColuna0(jB_L0C0.getText(), jB_L1C0.getText(), jB_L2C0.getText(), j2.getDesenho())
                        || op2.verificarColuna1(jB_L0C1.getText(), jB_L1C1.getText(), jB_L2C1.getText(), j2.getDesenho())
                        || op2.verificarColuna2(jB_L0C2.getText(), jB_L1C2.getText(), jB_L2C2.getText(), j2.getDesenho())
                        || op2.verificarLinha0(jB_L0C0.getText(), jB_L0C1.getText(), jB_L0C2.getText(), j2.getDesenho())
                        || op2.verificarLinha1(jB_L1C0.getText(), jB_L1C1.getText(), jB_L1C2.getText(), j2.getDesenho())
                        || op2.verificarLinha2(jB_L2C0.getText(), jB_L2C1.getText(), jB_L2C2.getText(), j2.getDesenho())) {
                    JOptionPane.showMessageDialog(rootPane, "Jogador 2 !", "Jogador Vencedor", 1);
                }else{
                    j2.setVez_jogada(false);
                    j1.setVez_jogada(true);
                    jTF_vez_jogada.setText("Jogador 1");
                }
            }
        }
    }//GEN-LAST:event_jB_L0C2MouseClicked

    private void jB_L1C0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_L1C0MouseClicked
        // TODO add your handling code here:
        if (j1.isVez_jogada()) {
            if (jB_L1C0.getText().equals("")) {
                jB_L1C0.setText(j1.getDesenho());

                Operacoes op1 = new Operacoes();
                if (op1.verificarDiagonalPrincipal(jB_L0C0.getText(), jB_L1C1.getText(), jB_L2C2.getText(), j1.getDesenho())
                        || op1.verificarDiagonalSecundaria(jB_L0C2.getText(), jB_L1C1.getText(), jB_L2C0.getText(), j1.getDesenho())
                        || op1.verificarColuna0(jB_L0C0.getText(), jB_L1C0.getText(), jB_L2C0.getText(), j1.getDesenho())
                        || op1.verificarColuna1(jB_L0C1.getText(), jB_L1C1.getText(), jB_L2C1.getText(), j1.getDesenho())
                        || op1.verificarColuna2(jB_L0C2.getText(), jB_L1C2.getText(), jB_L2C2.getText(), j1.getDesenho())
                        || op1.verificarLinha0(jB_L0C0.getText(), jB_L0C1.getText(), jB_L0C2.getText(), j1.getDesenho())
                        || op1.verificarLinha1(jB_L1C0.getText(), jB_L1C1.getText(), jB_L1C2.getText(), j1.getDesenho())
                        || op1.verificarLinha2(jB_L2C0.getText(), jB_L2C1.getText(), jB_L2C2.getText(), j1.getDesenho())) {
                    JOptionPane.showMessageDialog(rootPane, "Jogador 1 !", "Jogador Vencedor", 1);
                } else {
                    j1.setVez_jogada(false);
                    j2.setVez_jogada(true);
                    jTF_vez_jogada.setText("Jogador 2");
                }
            }
        }
        if (j2.isVez_jogada()) {
            if (jB_L1C0.getText().equals("")) {
                jB_L1C0.setText(j2.getDesenho());
                
                Operacoes op2 = new Operacoes();
                if (op2.verificarDiagonalPrincipal(jB_L0C0.getText(), jB_L1C1.getText(), jB_L2C2.getText(), j2.getDesenho())
                        || op2.verificarDiagonalSecundaria(jB_L0C2.getText(), jB_L1C1.getText(), jB_L2C0.getText(), j2.getDesenho())
                        || op2.verificarColuna0(jB_L0C0.getText(), jB_L1C0.getText(), jB_L2C0.getText(), j2.getDesenho())
                        || op2.verificarColuna1(jB_L0C1.getText(), jB_L1C1.getText(), jB_L2C1.getText(), j2.getDesenho())
                        || op2.verificarColuna2(jB_L0C2.getText(), jB_L1C2.getText(), jB_L2C2.getText(), j2.getDesenho())
                        || op2.verificarLinha0(jB_L0C0.getText(), jB_L0C1.getText(), jB_L0C2.getText(), j2.getDesenho())
                        || op2.verificarLinha1(jB_L1C0.getText(), jB_L1C1.getText(), jB_L1C2.getText(), j2.getDesenho())
                        || op2.verificarLinha2(jB_L2C0.getText(), jB_L2C1.getText(), jB_L2C2.getText(), j2.getDesenho())) {
                    JOptionPane.showMessageDialog(rootPane, "Jogador 2 !", "Jogador Vencedor", 1);
                }else{
                    j2.setVez_jogada(false);
                    j1.setVez_jogada(true);
                    jTF_vez_jogada.setText("Jogador 1");
                }
            }
        }
    }//GEN-LAST:event_jB_L1C0MouseClicked

    private void jB_L1C1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_L1C1MouseClicked
        // TODO add your handling code here:
        if (j1.isVez_jogada()) {
            if (jB_L1C1.getText().equals("")) {
                jB_L1C1.setText(j1.getDesenho());

                Operacoes op1 = new Operacoes();
                if (op1.verificarDiagonalPrincipal(jB_L0C0.getText(), jB_L1C1.getText(), jB_L2C2.getText(), j1.getDesenho())
                        || op1.verificarDiagonalSecundaria(jB_L0C2.getText(), jB_L1C1.getText(), jB_L2C0.getText(), j1.getDesenho())
                        || op1.verificarColuna0(jB_L0C0.getText(), jB_L1C0.getText(), jB_L2C0.getText(), j1.getDesenho())
                        || op1.verificarColuna1(jB_L0C1.getText(), jB_L1C1.getText(), jB_L2C1.getText(), j1.getDesenho())
                        || op1.verificarColuna2(jB_L0C2.getText(), jB_L1C2.getText(), jB_L2C2.getText(), j1.getDesenho())
                        || op1.verificarLinha0(jB_L0C0.getText(), jB_L0C1.getText(), jB_L0C2.getText(), j1.getDesenho())
                        || op1.verificarLinha1(jB_L1C0.getText(), jB_L1C1.getText(), jB_L1C2.getText(), j1.getDesenho())
                        || op1.verificarLinha2(jB_L2C0.getText(), jB_L2C1.getText(), jB_L2C2.getText(), j1.getDesenho())) {
                    JOptionPane.showMessageDialog(rootPane, "Jogador 1 !", "Jogador Vencedor", 1);
                } else {
                    j1.setVez_jogada(false);
                    j2.setVez_jogada(true);
                    jTF_vez_jogada.setText("Jogador 2");
                }
            }
        }
        if (j2.isVez_jogada()) {
            if (jB_L1C1.getText().equals("")) {
                jB_L1C1.setText(j2.getDesenho());
                
                Operacoes op2 = new Operacoes();
                if (op2.verificarDiagonalPrincipal(jB_L0C0.getText(), jB_L1C1.getText(), jB_L2C2.getText(), j2.getDesenho())
                        || op2.verificarDiagonalSecundaria(jB_L0C2.getText(), jB_L1C1.getText(), jB_L2C0.getText(), j2.getDesenho())
                        || op2.verificarColuna0(jB_L0C0.getText(), jB_L1C0.getText(), jB_L2C0.getText(), j2.getDesenho())
                        || op2.verificarColuna1(jB_L0C1.getText(), jB_L1C1.getText(), jB_L2C1.getText(), j2.getDesenho())
                        || op2.verificarColuna2(jB_L0C2.getText(), jB_L1C2.getText(), jB_L2C2.getText(), j2.getDesenho())
                        || op2.verificarLinha0(jB_L0C0.getText(), jB_L0C1.getText(), jB_L0C2.getText(), j2.getDesenho())
                        || op2.verificarLinha1(jB_L1C0.getText(), jB_L1C1.getText(), jB_L1C2.getText(), j2.getDesenho())
                        || op2.verificarLinha2(jB_L2C0.getText(), jB_L2C1.getText(), jB_L2C2.getText(), j2.getDesenho())) {
                    JOptionPane.showMessageDialog(rootPane, "Jogador 2 !", "Jogador Vencedor", 1);
                }else{
                    j2.setVez_jogada(false);
                    j1.setVez_jogada(true);
                    jTF_vez_jogada.setText("Jogador 1");
                }
            }
        }
    }//GEN-LAST:event_jB_L1C1MouseClicked

    private void jB_L1C2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_L1C2MouseClicked
        // TODO add your handling code here:
        if (j1.isVez_jogada()) {
            if (jB_L1C2.getText().equals("")) {
                jB_L1C2.setText(j1.getDesenho());

                Operacoes op1 = new Operacoes();
                if (op1.verificarDiagonalPrincipal(jB_L0C0.getText(), jB_L1C1.getText(), jB_L2C2.getText(), j1.getDesenho())
                        || op1.verificarDiagonalSecundaria(jB_L0C2.getText(), jB_L1C1.getText(), jB_L2C0.getText(), j1.getDesenho())
                        || op1.verificarColuna0(jB_L0C0.getText(), jB_L1C0.getText(), jB_L2C0.getText(), j1.getDesenho())
                        || op1.verificarColuna1(jB_L0C1.getText(), jB_L1C1.getText(), jB_L2C1.getText(), j1.getDesenho())
                        || op1.verificarColuna2(jB_L0C2.getText(), jB_L1C2.getText(), jB_L2C2.getText(), j1.getDesenho())
                        || op1.verificarLinha0(jB_L0C0.getText(), jB_L0C1.getText(), jB_L0C2.getText(), j1.getDesenho())
                        || op1.verificarLinha1(jB_L1C0.getText(), jB_L1C1.getText(), jB_L1C2.getText(), j1.getDesenho())
                        || op1.verificarLinha2(jB_L2C0.getText(), jB_L2C1.getText(), jB_L2C2.getText(), j1.getDesenho())) {
                    JOptionPane.showMessageDialog(rootPane, "Jogador 1 !", "Jogador Vencedor", 1);
                } else {
                    j1.setVez_jogada(false);
                    j2.setVez_jogada(true);
                    jTF_vez_jogada.setText("Jogador 2");
                }
            }
        }
        if (j2.isVez_jogada()) {
            if (jB_L1C2.getText().equals("")) {
                jB_L1C2.setText(j2.getDesenho());
                
                Operacoes op2 = new Operacoes();
                if (op2.verificarDiagonalPrincipal(jB_L0C0.getText(), jB_L1C1.getText(), jB_L2C2.getText(), j2.getDesenho())
                        || op2.verificarDiagonalSecundaria(jB_L0C2.getText(), jB_L1C1.getText(), jB_L2C0.getText(), j2.getDesenho())
                        || op2.verificarColuna0(jB_L0C0.getText(), jB_L1C0.getText(), jB_L2C0.getText(), j2.getDesenho())
                        || op2.verificarColuna1(jB_L0C1.getText(), jB_L1C1.getText(), jB_L2C1.getText(), j2.getDesenho())
                        || op2.verificarColuna2(jB_L0C2.getText(), jB_L1C2.getText(), jB_L2C2.getText(), j2.getDesenho())
                        || op2.verificarLinha0(jB_L0C0.getText(), jB_L0C1.getText(), jB_L0C2.getText(), j2.getDesenho())
                        || op2.verificarLinha1(jB_L1C0.getText(), jB_L1C1.getText(), jB_L1C2.getText(), j2.getDesenho())
                        || op2.verificarLinha2(jB_L2C0.getText(), jB_L2C1.getText(), jB_L2C2.getText(), j2.getDesenho())) {
                    JOptionPane.showMessageDialog(rootPane, "Jogador 2 !", "Jogador Vencedor", 1);
                }else{
                    j2.setVez_jogada(false);
                    j1.setVez_jogada(true);
                    jTF_vez_jogada.setText("Jogador 1");
                }
            }
        }
    }//GEN-LAST:event_jB_L1C2MouseClicked

    private void jB_L2C0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_L2C0MouseClicked
        // TODO add your handling code here:
        if (j1.isVez_jogada()) {
            if (jB_L2C0.getText().equals("")) {
                jB_L2C0.setText(j1.getDesenho());

                Operacoes op1 = new Operacoes();
                if (op1.verificarDiagonalPrincipal(jB_L0C0.getText(), jB_L1C1.getText(), jB_L2C2.getText(), j1.getDesenho())
                        || op1.verificarDiagonalSecundaria(jB_L0C2.getText(), jB_L1C1.getText(), jB_L2C0.getText(), j1.getDesenho())
                        || op1.verificarColuna0(jB_L0C0.getText(), jB_L1C0.getText(), jB_L2C0.getText(), j1.getDesenho())
                        || op1.verificarColuna1(jB_L0C1.getText(), jB_L1C1.getText(), jB_L2C1.getText(), j1.getDesenho())
                        || op1.verificarColuna2(jB_L0C2.getText(), jB_L1C2.getText(), jB_L2C2.getText(), j1.getDesenho())
                        || op1.verificarLinha0(jB_L0C0.getText(), jB_L0C1.getText(), jB_L0C2.getText(), j1.getDesenho())
                        || op1.verificarLinha1(jB_L1C0.getText(), jB_L1C1.getText(), jB_L1C2.getText(), j1.getDesenho())
                        || op1.verificarLinha2(jB_L2C0.getText(), jB_L2C1.getText(), jB_L2C2.getText(), j1.getDesenho())) {
                    JOptionPane.showMessageDialog(rootPane, "Jogador 1 !", "Jogador Vencedor", 1);
                } else {
                    j1.setVez_jogada(false);
                    j2.setVez_jogada(true);
                    jTF_vez_jogada.setText("Jogador 2");
                }
            }
        }
        if (j2.isVez_jogada()) {
            if (jB_L2C0.getText().equals("")) {
                jB_L2C0.setText(j2.getDesenho());
                
                Operacoes op2 = new Operacoes();
                if (op2.verificarDiagonalPrincipal(jB_L0C0.getText(), jB_L1C1.getText(), jB_L2C2.getText(), j2.getDesenho())
                        || op2.verificarDiagonalSecundaria(jB_L0C2.getText(), jB_L1C1.getText(), jB_L2C0.getText(), j2.getDesenho())
                        || op2.verificarColuna0(jB_L0C0.getText(), jB_L1C0.getText(), jB_L2C0.getText(), j2.getDesenho())
                        || op2.verificarColuna1(jB_L0C1.getText(), jB_L1C1.getText(), jB_L2C1.getText(), j2.getDesenho())
                        || op2.verificarColuna2(jB_L0C2.getText(), jB_L1C2.getText(), jB_L2C2.getText(), j2.getDesenho())
                        || op2.verificarLinha0(jB_L0C0.getText(), jB_L0C1.getText(), jB_L0C2.getText(), j2.getDesenho())
                        || op2.verificarLinha1(jB_L1C0.getText(), jB_L1C1.getText(), jB_L1C2.getText(), j2.getDesenho())
                        || op2.verificarLinha2(jB_L2C0.getText(), jB_L2C1.getText(), jB_L2C2.getText(), j2.getDesenho())) {
                    JOptionPane.showMessageDialog(rootPane, "Jogador 2 !", "Jogador Vencedor", 1);
                }else{
                    j2.setVez_jogada(false);
                    j1.setVez_jogada(true);
                    jTF_vez_jogada.setText("Jogador 1");
                }
            }
        }
    }//GEN-LAST:event_jB_L2C0MouseClicked

    private void jB_L2C1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_L2C1MouseClicked
        // TODO add your handling code here:
        if (j1.isVez_jogada()) {
            if (jB_L2C1.getText().equals("")) {
                jB_L2C1.setText(j1.getDesenho());

                Operacoes op1 = new Operacoes();
                if (op1.verificarDiagonalPrincipal(jB_L0C0.getText(), jB_L1C1.getText(), jB_L2C2.getText(), j1.getDesenho())
                        || op1.verificarDiagonalSecundaria(jB_L0C2.getText(), jB_L1C1.getText(), jB_L2C0.getText(), j1.getDesenho())
                        || op1.verificarColuna0(jB_L0C0.getText(), jB_L1C0.getText(), jB_L2C0.getText(), j1.getDesenho())
                        || op1.verificarColuna1(jB_L0C1.getText(), jB_L1C1.getText(), jB_L2C1.getText(), j1.getDesenho())
                        || op1.verificarColuna2(jB_L0C2.getText(), jB_L1C2.getText(), jB_L2C2.getText(), j1.getDesenho())
                        || op1.verificarLinha0(jB_L0C0.getText(), jB_L0C1.getText(), jB_L0C2.getText(), j1.getDesenho())
                        || op1.verificarLinha1(jB_L1C0.getText(), jB_L1C1.getText(), jB_L1C2.getText(), j1.getDesenho())
                        || op1.verificarLinha2(jB_L2C0.getText(), jB_L2C1.getText(), jB_L2C2.getText(), j1.getDesenho())) {
                    JOptionPane.showMessageDialog(rootPane, "Jogador 1 !", "Jogador Vencedor", 1);
                } else {
                    j1.setVez_jogada(false);
                    j2.setVez_jogada(true);
                    jTF_vez_jogada.setText("Jogador 2");
                }
            }
        }
        if (j2.isVez_jogada()) {
            if (jB_L2C1.getText().equals("")) {
                jB_L2C1.setText(j2.getDesenho());
                
                Operacoes op2 = new Operacoes();
                if (op2.verificarDiagonalPrincipal(jB_L0C0.getText(), jB_L1C1.getText(), jB_L2C2.getText(), j2.getDesenho())
                        || op2.verificarDiagonalSecundaria(jB_L0C2.getText(), jB_L1C1.getText(), jB_L2C0.getText(), j2.getDesenho())
                        || op2.verificarColuna0(jB_L0C0.getText(), jB_L1C0.getText(), jB_L2C0.getText(), j2.getDesenho())
                        || op2.verificarColuna1(jB_L0C1.getText(), jB_L1C1.getText(), jB_L2C1.getText(), j2.getDesenho())
                        || op2.verificarColuna2(jB_L0C2.getText(), jB_L1C2.getText(), jB_L2C2.getText(), j2.getDesenho())
                        || op2.verificarLinha0(jB_L0C0.getText(), jB_L0C1.getText(), jB_L0C2.getText(), j2.getDesenho())
                        || op2.verificarLinha1(jB_L1C0.getText(), jB_L1C1.getText(), jB_L1C2.getText(), j2.getDesenho())
                        || op2.verificarLinha2(jB_L2C0.getText(), jB_L2C1.getText(), jB_L2C2.getText(), j2.getDesenho())) {
                    JOptionPane.showMessageDialog(rootPane, "Jogador 2 !", "Jogador Vencedor", 1);
                }else{
                    j2.setVez_jogada(false);
                    j1.setVez_jogada(true);
                    jTF_vez_jogada.setText("Jogador 1");
                }
            }
        }
    }//GEN-LAST:event_jB_L2C1MouseClicked

    private void jB_L2C2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_L2C2MouseClicked
        // TODO add your handling code here:
        if (j1.isVez_jogada()) {
            if (jB_L2C2.getText().equals("")) {
                jB_L2C2.setText(j1.getDesenho());

                Operacoes op1 = new Operacoes();
                if (op1.verificarDiagonalPrincipal(jB_L0C0.getText(), jB_L1C1.getText(), jB_L2C2.getText(), j1.getDesenho())
                        || op1.verificarDiagonalSecundaria(jB_L0C2.getText(), jB_L1C1.getText(), jB_L2C0.getText(), j1.getDesenho())
                        || op1.verificarColuna0(jB_L0C0.getText(), jB_L1C0.getText(), jB_L2C0.getText(), j1.getDesenho())
                        || op1.verificarColuna1(jB_L0C1.getText(), jB_L1C1.getText(), jB_L2C1.getText(), j1.getDesenho())
                        || op1.verificarColuna2(jB_L0C2.getText(), jB_L1C2.getText(), jB_L2C2.getText(), j1.getDesenho())
                        || op1.verificarLinha0(jB_L0C0.getText(), jB_L0C1.getText(), jB_L0C2.getText(), j1.getDesenho())
                        || op1.verificarLinha1(jB_L1C0.getText(), jB_L1C1.getText(), jB_L1C2.getText(), j1.getDesenho())
                        || op1.verificarLinha2(jB_L2C0.getText(), jB_L2C1.getText(), jB_L2C2.getText(), j1.getDesenho())) {
                    JOptionPane.showMessageDialog(rootPane, "Jogador 1 !", "Jogador Vencedor", 1);
                } else {
                    j1.setVez_jogada(false);
                    j2.setVez_jogada(true);
                    jTF_vez_jogada.setText("Jogador 2");
                }
            }
        }
        if (j2.isVez_jogada()) {
            if (jB_L2C2.getText().equals("")) {
                jB_L2C2.setText(j2.getDesenho());
                
                Operacoes op2 = new Operacoes();
                if (op2.verificarDiagonalPrincipal(jB_L0C0.getText(), jB_L1C1.getText(), jB_L2C2.getText(), j2.getDesenho())
                        || op2.verificarDiagonalSecundaria(jB_L0C2.getText(), jB_L1C1.getText(), jB_L2C0.getText(), j2.getDesenho())
                        || op2.verificarColuna0(jB_L0C0.getText(), jB_L1C0.getText(), jB_L2C0.getText(), j2.getDesenho())
                        || op2.verificarColuna1(jB_L0C1.getText(), jB_L1C1.getText(), jB_L2C1.getText(), j2.getDesenho())
                        || op2.verificarColuna2(jB_L0C2.getText(), jB_L1C2.getText(), jB_L2C2.getText(), j2.getDesenho())
                        || op2.verificarLinha0(jB_L0C0.getText(), jB_L0C1.getText(), jB_L0C2.getText(), j2.getDesenho())
                        || op2.verificarLinha1(jB_L1C0.getText(), jB_L1C1.getText(), jB_L1C2.getText(), j2.getDesenho())
                        || op2.verificarLinha2(jB_L2C0.getText(), jB_L2C1.getText(), jB_L2C2.getText(), j2.getDesenho())) {
                    JOptionPane.showMessageDialog(rootPane, "Jogador 2 !", "Jogador Vencedor", 1);
                }else{
                    j2.setVez_jogada(false);
                    j1.setVez_jogada(true);
                    jTF_vez_jogada.setText("Jogador 1");
                }
            }
        }
    }//GEN-LAST:event_jB_L2C2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        /*jTF_pontos_jogador_1.setText("0");
        jTF_pontos_jogador_2.setText("0");

        // INICIA PARTIDA COM O JOGADOR INICIANTE
        if (j1.isVez_jogada()) {
            jTF_vez_jogada.setText("Jogador 1");
        }
        if (j2.isVez_jogada()) {
            jTF_vez_jogada.setText("Jogador 2");
        }
        */
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_L0C0;
    private javax.swing.JButton jB_L0C1;
    private javax.swing.JButton jB_L0C2;
    private javax.swing.JButton jB_L1C0;
    private javax.swing.JButton jB_L1C1;
    private javax.swing.JButton jB_L1C2;
    private javax.swing.JButton jB_L2C0;
    private javax.swing.JButton jB_L2C1;
    private javax.swing.JButton jB_L2C2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTF_vez_jogada;
    // End of variables declaration//GEN-END:variables
}
